set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN F15 [get_ports reset_n]

set_property IOSTANDARD LVCMOS33 [get_ports {AD0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[0]}]
set_property PACKAGE_PIN 	C18	[get_ports {AD0[7]}]
set_property PACKAGE_PIN 	C19	[get_ports {AD0[6]}]
set_property PACKAGE_PIN 	B17	[get_ports {AD0[5]}]
set_property PACKAGE_PIN 	B18	[get_ports {AD0[4]}]
set_property PACKAGE_PIN 	E16	[get_ports {AD0[3]}]
set_property PACKAGE_PIN 	D16	[get_ports {AD0[2]}]
set_property PACKAGE_PIN 	D17	[get_ports {AD0[1]}]
set_property PACKAGE_PIN 	C17	[get_ports {AD0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports AD0_CLK]
set_property PACKAGE_PIN 	F16	[get_ports AD0_CLK]


set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[0]}]
set_property PACKAGE_PIN 	A13	[get_ports {DA0_Data[7]}]
set_property PACKAGE_PIN 	A16	[get_ports {DA0_Data[6]}]
set_property PACKAGE_PIN 	A15	[get_ports {DA0_Data[5]}]
set_property PACKAGE_PIN 	A19	[get_ports {DA0_Data[4]}]
set_property PACKAGE_PIN 	A18	[get_ports {DA0_Data[3]}]
set_property PACKAGE_PIN 	F14	[get_ports {DA0_Data[2]}]
set_property PACKAGE_PIN 	F13	[get_ports {DA0_Data[1]}]
set_property PACKAGE_PIN 	E14	[get_ports {DA0_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DA0_Clk]
set_property PACKAGE_PIN 	A14	[get_ports DA0_Clk]


set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[0]}]
set_property PACKAGE_PIN 	C13	[get_ports {DA1_Data[7]}]
set_property PACKAGE_PIN 	B13	[get_ports {DA1_Data[6]}]
set_property PACKAGE_PIN 	D14	[get_ports {DA1_Data[5]}]
set_property PACKAGE_PIN 	D15	[get_ports {DA1_Data[4]}]
set_property PACKAGE_PIN 	C14	[get_ports {DA1_Data[3]}]
set_property PACKAGE_PIN 	C15	[get_ports {DA1_Data[2]}]
set_property PACKAGE_PIN 	B15	[get_ports {DA1_Data[1]}]
set_property PACKAGE_PIN 	B16	[get_ports {DA1_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DA1_Clk]
set_property PACKAGE_PIN 	E13	[get_ports DA1_Clk]